version: '3.7'

volumes:
  local_postgres_data: {}

services:
  postgres:
    container_name: 'postgresql'
    image: postgres:13-alpine
    networks:
      - common
    env_file:
      - .postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

  django:
    container_name: 'django'
    build: .
    depends_on:
      - postgres
    restart: always
    ports:
      - 8000:8000
    command: sh -c "pytest && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - common

networks:
  common:
    name: common